
//Set path to SmartSlog KP Library
#include <smartslog/generic.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_HASSURNAME 1
#define INCLUDE_PROPERTY_HASCONTENT 1
#define INCLUDE_PROPERTY_HASID 1
#define INCLUDE_PROPERTY_HASNAME 1
#define INCLUDE_PROPERTY_HASPATRONYMIC 1
#define INCLUDE_PROPERTY_HASCITY 1
#define INCLUDE_CLASS_USER 1
#define INCLUDE_CLASS_USERPAGE 1
#define INCLUDE_CLASS_NOTHING 1
#define INCLUDE_CLASS_PAGE 1
#define INCLUDE_CLASS_MAPPAGE 1
#define INCLUDE_CLASS_THING 1


#else

#define INCLUDE_PROPERTY_HASSURNAME 0
#define INCLUDE_PROPERTY_HASCONTENT 0
#define INCLUDE_PROPERTY_HASID 0
#define INCLUDE_PROPERTY_HASNAME 0
#define INCLUDE_PROPERTY_HASPATRONYMIC 0
#define INCLUDE_PROPERTY_HASCITY 0
#define INCLUDE_CLASS_USER 0
#define INCLUDE_CLASS_USERPAGE 0
#define INCLUDE_CLASS_NOTHING 0
#define INCLUDE_CLASS_PAGE 0
#define INCLUDE_CLASS_MAPPAGE 0
#define INCLUDE_CLASS_THING 0


#endif


#if INCLUDE_CLASS_USER
extern class_t *CLASS_USER;
#endif
#if INCLUDE_CLASS_USERPAGE
extern class_t *CLASS_USERPAGE;
#endif
#if INCLUDE_CLASS_NOTHING
extern class_t *CLASS_NOTHING;
#endif
#if INCLUDE_CLASS_PAGE
extern class_t *CLASS_PAGE;
#endif
#if INCLUDE_CLASS_MAPPAGE
extern class_t *CLASS_MAPPAGE;
#endif
#if INCLUDE_CLASS_THING
extern class_t *CLASS_THING;
#endif


#if INCLUDE_PROPERTY_HASSURNAME
extern property_t *PROPERTY_HASSURNAME;
#endif
#if INCLUDE_PROPERTY_HASCONTENT
extern property_t *PROPERTY_HASCONTENT;
#endif
#if INCLUDE_PROPERTY_HASID
extern property_t *PROPERTY_HASID;
#endif
#if INCLUDE_PROPERTY_HASNAME
extern property_t *PROPERTY_HASNAME;
#endif
#if INCLUDE_PROPERTY_HASPATRONYMIC
extern property_t *PROPERTY_HASPATRONYMIC;
#endif
#if INCLUDE_PROPERTY_HASCITY
extern property_t *PROPERTY_HASCITY;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */
